[
    {
        "student_type": "Student",
        "student_id": "001",
        "name": "Ziyadinkhan",
        "age": 18,
        "email": "ziyadin2309@gmail.com",
        "phone": "+77750401515",
        "major": "Software Engineering",
        "year_level": 1,
        "status": "Active",
        "grades": [],
        "attendance": []
    },
    {
        "student_type": "Student",
        "student_id": "002",
        "name": "Alisher",
        "age": 20,
        "email": "alsiher@mail.ru",
        "phone": "+77772551885",
        "major": "Comoputer Science",
        "year_level": 1,
        "status": "Active",
        "grades": [],
        "attendance": []
    }
]